export const LAYOUT_SET_DATA = 'LAYOUT_SET_DATA';
export const LAYOUT_CLEAR_DATA = 'LAYOUT_CLEAR_DATA';

export const LAYOUT_SELECT_ELEMENTS = 'LAYOUT_SELECT_ELEMENTS';
export const LAYOUT_HOVER_ELEMENTS = 'LAYOUT_HOVER_ELEMENTS';

export const LAYOUT_ADD_SECTION = 'LAYOUT_ADD_SECTION';
export const LAYOUT_EDIT_SECTION = 'LAYOUT_EDIT_SECTION';
export const LAYOUT_REMOVE_SECTION = 'LAYOUT_REMOVE_SECTION';

export const LAYOUT_EDIT_COLUMN = 'LAYOUT_EDIT_COLUMN';
export const LAYOUT_MOVE_COLUMN = 'LAYOUT_MOVE_COLUMN';
