export const LAYOUT_SET_DATA = 'LAYOUT_SET_DATA';
export const LAYOUT_CLEAR_DATA = 'LAYOUT_CLEAR_DATA';

export const LAYOUT_SET_SETTINGS = 'LAYOUT_SET_SETTINGS';

export const LAYOUT_SET_SELECT = 'LAYOUT_SET_SELECT';
export const LAYOUT_SET_SELECT_SOME = 'LAYOUT_SET_SELECT_SOME';
export const LAYOUT_CLEAR_SELECTS = 'LAYOUT_CLEAR_SELECTS';

export const LAYOUT_GROUP_ELEMENTS = 'LAYOUT_GROUP_ELEMENTS';
export const LAYOUT_UNGROUP_ELEMENTS = 'LAYOUT_UNGROUP_ELEMENTS';

export const LAYOUT_RESIZE_GROUP_ELEMENT = 'LAYOUT_RESIZE_GROUP_ELEMENT';
export const LAYOUT_MOVE_SELECT_CONTAINER = 'LAYOUT_MOVE_SELECT_CONTAINER';
export const LAYOUT_RESIZE_SELECT_CONTAINER = 'LAYOUT_RESIZE_SELECT_CONTAINER';


export const LAYOUT_ADD_ELEMENT = 'LAYOUT_ADD_ELEMENT';
export const LAYOUT_ADD_TEMPLATE = 'LAYOUT_ADD_TEMPLATE';
export const LAYOUT_CHANGE_TEMPLATE_LINK = 'LAYOUT_CHANGE_TEMPLATE_LINK';
export const LAYOUT_EDIT_ELEMENT = 'LAYOUT_EDIT_ELEMENT';
export const LAYOUT_DELETE_ELEMENT = 'LAYOUT_DELETE_ELEMENT';


