export const LAYOUT_SET_DATA = 'LAYOUT_SET_DATA';
export const LAYOUT_CLEAR_DATA = 'LAYOUT_CLEAR_DATA';

export const LAYOUT_HOVER_SECTION = 'LAYOUT_HOVER_SECTION';
export const LAYOUT_SELECT_ELEMENTS = 'LAYOUT_SELECT_ELEMENTS';
