export const GRAPH_SET_DATA = 'GRAPH_SET_DATA';
export const GRAPH_SET_POSITION_LAYOUT = 'GRAPH_SET_POSITION_LAYOUT';
export const GRAPH_SET_POSITION_CONTAINER = 'GRAPH_SET_POSITION_CONTAINER';

export const GRAPH_SET_POSITION_GROUP_CONTAINER = 'GRAPH_SET_POSITION_GROUP_CONTAINER';
export const GRAPH_SET_RESIZE_GROUP_CONTAINER = 'GRAPH_SET_RESIZE_GROUP_CONTAINER';
export const GRAPH_SET_SETTINGS_CONTAINER = 'GRAPH_SET_SETTINGS_CONTAINER';

export const GRAPH_ADD_CONTAINER = 'GRAPH_ADD_CONTAINER';
export const GRAPH_SELECT_BLOCK_CONTAINER = 'GRAPH_SELECT_BLOCK_CONTAINER';
export const GRAPH_SELECT_ONE_CONTAINER = 'GRAPH_SELECT_ONE_CONTAINER';
export const GRAPH_SELECT_MULTI_CONTAINERS = 'GRAPH_SELECT_MULTI_CONTAINERS';
export const GRAPH_CLEAR_ALL_SELECTS = 'GRAPH_CLEAR_ALL_SELECTS';


