export const GRAPH_SET_DATA = 'GRAPH_SET_DATA';
export const GRAPH_FORCE_DATA = 'GRAPH_FORCE_DATA';

export const GRAPH_SET_POSITION_LAYOUT = 'GRAPH_SET_POSITION_LAYOUT';
export const GRAPH_SET_POSITION_CONTAINER = 'GRAPH_SET_POSITION_CONTAINER';
export const GRAPH_SET_PROPERTIES_CONTAINER = 'GRAPH_SET_PROPERTIES_CONTAINER';


export const GRAPH_SET_POSITION_GROUP_CONTAINER = 'GRAPH_SET_POSITION_GROUP_CONTAINER';
export const GRAPH_SET_RESIZE_GROUP_CONTAINER = 'GRAPH_SET_RESIZE_GROUP_CONTAINER';
export const GRAPH_SET_SETTINGS_CONTAINER = 'GRAPH_SET_SETTINGS_CONTAINER';

export const GRAPH_ADD_CONTAINER = 'GRAPH_ADD_CONTAINER';
export const GRAPH_SELECT_BLOCK = 'GRAPH_SELECT_BLOCK';
export const GRAPH_SELECT_ONE_CONTAINER = 'GRAPH_SELECT_ONE_CONTAINER';
export const GRAPH_SELECT_MULTI_CONTAINERS = 'GRAPH_SELECT_MULTI_CONTAINERS';
export const GRAPH_CLEAR_ALL_SELECTS = 'GRAPH_CLEAR_ALL_SELECTS';

export const GRAPH_SET_GROUP = 'GRAPH_SET_GROUP';
export const GRAPH_UNSET_GROUP = 'GRAPH_UNSET_GROUP';


