export const APP_TABS_SET_DATA = 'APP_TABS_SET_DATA';
export const APP_TABS_SET_SELECT = 'APP_TABS_SET_SELECT';

export const APP_TABS_ADD_ITEM = 'APP_TABS_ADD_ITEM';
export const APP_TABS_REMOVE_ITEM = 'APP_TABS_REMOVE_ITEM';