export const APP_NAV_SET_DATA = 'APP_NAV_SET_DATA';

export const APP_NAV_SELECT_NODE = 'APP_NAV_SELECT_NODE';
export const APP_NAV_SELECT_NODES = 'APP_NAV_SELECT_NODES';
export const APP_NAV_CLEAR_SELECTED = 'APP_NAV_CLEAR_SELECTED';

export const APP_NAV_ADD_NODE = 'APP_NAV_ADD_NODE';
export const APP_NAV_SET_PANEL_WIDTH = 'APP_NAV_SET_PANEL_WIDTH';