export const DIALOG_SET_DATA = 'DIALOG_SET_DATA';
export const DIALOG_CLEAR_DATA = 'DIALOG_CLEAR_DATA';

export const DIALOG_SET_SETTINGS = 'DIALOG_SET_SETTINGS';

export const DIALOG_SET_SELECT = 'DIALOG_SET_SELECT';
export const DIALOG_SET_SELECT_SOME = 'DIALOG_SET_SELECT_SOME';
export const DIALOG_CLEAR_SELECTS = 'DIALOG_CLEAR_SELECTS';

export const DIALOG_GROUP_ELEMENTS = 'DIALOG_GROUP_ELEMENTS';
export const DIALOG_UNGROUP_ELEMENTS = 'DIALOG_UNGROUP_ELEMENTS';

export const DIALOG_RESIZE_GROUP_ELEMENT = 'DIALOG_RESIZE_GROUP_ELEMENT';
export const DIALOG_MOVE_SELECT_CONTAINER = 'DIALOG_MOVE_SELECT_CONTAINER';
export const DIALOG_RESIZE_SELECT_CONTAINER = 'DIALOG_RESIZE_SELECT_CONTAINER';


export const DIALOG_ADD_ELEMENT = 'DIALOG_ADD_ELEMENT';
export const DIALOG_ADD_TEMPLATE = 'DIALOG_ADD_TEMPLATE';
export const DIALOG_CHANGE_TEMPLATE = 'DIALOG_CHANGE_TEMPLATE';
export const DIALOG_EDIT_ELEMENT = 'DIALOG_EDIT_ELEMENT';
export const DIALOG_DELETE_ELEMENT = 'DIALOG_DELETE_ELEMENT';


