export const FORM_SET_ERRORS = 'FORM_SET_ERRORS';
export const FORM_SET_CACHE = 'FORM_SET_CACHE'
export const FORM_SET_VALUE_BASIC = 'FORM_SET_VALUE_BASIC'
export const FORM_SET_VALUE_TABLE = 'FORM_SET_VALUE_TABLE'