export const FORM_SET_ERRORS = 'FORM_SET_ERRORS';

export const FORM_SET_VALUE_BASIC = 'FORM_SET_VALUE_BASIC';
export const FORM_SET_VALUE_TABLE = 'FORM_SET_VALUE_TABLE';

export const FORM_ADD_ROW_TABLE = 'FORM_ADD_ROW_TABLE';
export const FORM_REMOVE_ROW_TABLE = 'FORM_REMOVE_ROW_TABLE';