export const APP_PAGE_SET_DATA = 'APP_PAGE_SET_DATA';
export const APP_PAGE_SET_VALUE_FORM_BASIC = 'APP_PAGE_SET_VALUE_FORM_BASIC'

export const APP_PAGE_SET_VALUE_FORM_TABLE = 'APP_PAGE_SET_VALUE_FORM_TABLE'