export const APP_PAGE_SET_DATA = 'APP_PAGE_SET_DATA';
export const APP_PAGE_SET_ERRORS_FORM = 'APP_PAGE_SET_ERRORS_FORM';


export const APP_PAGE_SET_VALUE_CACHE_FORM = 'APP_PAGE_SET_VALUE_CACHE_FORM'
export const APP_PAGE_SET_VALUE_FORM_BASIC = 'APP_PAGE_SET_VALUE_FORM_BASIC'
export const APP_PAGE_SET_VALUE_FORM_TABLE = 'APP_PAGE_SET_VALUE_FORM_TABLE'