export const APP_DIALOG_SET_DATA = 'APP_DIALOG_SET_DATA';
export const APP_DIALOG_CLOSE = 'APP_DIALOG_CLOSE';

export const APP_DIALOG_SET_COMPONENT = 'APP_DIALOG_SET_COMPONENT';
export const APP_DIALOG_SET_FORM = 'APP_DIALOG_SET_FORM';

export const APP_DIALOG_FORM_SET_ERRORS = 'APP_DIALOG_FORM_SET_ERRORS';

export const APP_DIALOG_FORM_SET_VALUE_BASIC = 'APP_DIALOG_FORM_SET_VALUE_BASIC';
export const APP_DIALOG_FORM_SET_VALUE_TABLE = 'APP_DIALOG_FORM_SET_VALUE_TABLE';

export const APP_DIALOG_FORM_ADD_ROW_TABLE = 'APP_DIALOG_FORM_ADD_ROW_TABLE';
export const APP_DIALOG_FORM_REMOVE_ROW_TABLE = 'APP_DIALOG_FORM_REMOVE_ROW_TABLE';