export const APP_DIALOG_SET_DATA = 'APP_DIALOG_SET_DATA';
export const APP_DIALOG_CLOSE = 'APP_DIALOG_CLOSE';

export const APP_DIALOG_SET_COMPONENT = 'APP_DIALOG_SET_COMPONENT';
export const APP_DIALOG_SET_FORM = 'APP_DIALOG_SET_FORM';
