export const LAYOUT_SET_DATA = 'LAYOUT_SET_DATA';
export const LAYOUT_FORCE_DATA = 'LAYOUT_FORCE_DATA';

export const LAYOUT_SECTION_OUT = 'LAYOUT_SECTION_OUT';
export const LAYOUT_COLUMN_OVER = 'LAYOUT_COLUMN_OVER';
