export const LAYOUT_SET_DATA = 'LAYOUT_SET_DATA';
export const LAYOUT_FORCE_DATA = 'LAYOUT_FORCE_DATA';

export const LAYOUT_SECTION_DRAG_START = 'LAYOUT_SECTION_DRAG_START';
export const LAYOUT_SECTION_DRAG_STOP = 'LAYOUT_SECTION_DRAG_STOP';
export const LAYOUT_SECTION_DRAG_MOVE = 'LAYOUT_SECTION_DRAG_MOVE';
export const LAYOUT_SECTION_DRAG_UPDATE = 'LAYOUT_SECTION_DRAG_UPDATE';

export const LAYOUT_SECTION_OUT = 'LAYOUT_SECTION_OUT';
export const LAYOUT_COLUMN_OVER = 'LAYOUT_COLUMN_OVER';
export const LAYOUT_COLUMN_ACTIVE = 'LAYOUT_COLUMN_ACTIVE';