export const APP_LAYOUT_SET_DATA = 'APP_LAYOUT_SET_DATA';

export const APP_LAYOUT_UPDATE_ELEMENTS = 'APP_LAYOUT_UPDATE_ELEMENTS';
export const APP_LAYOUT_UPDATE_TEMPLATES = 'APP_LAYOUT_UPDATE_TEMPLATES';

export const APP_LAYOUT_SYNC_CHARTS_LAYOUT = 'APP_LAYOUT_SYNC_CHARTS_LAYOUT';
export const APP_LAYOUT_SYNC_CHARTS_CONTAINER = 'APP_LAYOUT_SYNC_CHARTS_CONTAINER';

export const APP_LAYOUT_CHANGE_CONTAINER = 'APP_LAYOUT_CHANGE_CONTAINER';

