export const CONTAINER_SET_DATA = 'CONTAINER_SET_DATA';
export const CONTAINER_CLEAR_DATA = 'CONTAINER_CLEAR_DATA';

export const CONTAINER_SET_SELECT = 'CONTAINER_SET_SELECT';
export const CONTAINER_CLEAR_SELECTS = 'CONTAINER_CLEAR_SELECTS';

export const CONTAINER_SET_SETTINGS = 'CONTAINER_SET_SETTINGS';
export const CONTAINER_EDIT_ELEMENT = 'CONTAINER_EDIT_ELEMENT';

