export const CONTAINER_SET_DATA = 'CONTAINER_SET_DATA';
export const CONTAINER_CLEAR_DATA = 'CONTAINER_CLEAR_DATA';

export const CONTAINER_SET_SETTINGS = 'CONTAINER_SET_SETTINGS';

export const CONTAINER_SET_SELECT = 'CONTAINER_SET_SELECT';
export const CONTAINER_SET_SELECT_SOME = 'CONTAINER_SET_SELECT_SOME';
export const CONTAINER_CLEAR_SELECTS = 'CONTAINER_CLEAR_SELECTS';

export const CONTAINER_GROUP_ELEMENTS = 'CONTAINER_GROUP_ELEMENTS';
export const CONTAINER_UNGROUP_ELEMENTS = 'CONTAINER_UNGROUP_ELEMENTS';

export const CONTAINER_RESIZE_GROUP_ELEMENT = 'CONTAINER_RESIZE_GROUP_ELEMENT';
export const CONTAINER_MOVE_SELECT_CONTAINER = 'CONTAINER_MOVE_SELECT_CONTAINER';
export const CONTAINER_RESIZE_SELECT_CONTAINER = 'CONTAINER_RESIZE_SELECT_CONTAINER';


export const CONTAINER_ADD_ELEMENT = 'CONTAINER_ADD_ELEMENT';
export const CONTAINER_ADD_TEMPLATE = 'CONTAINER_ADD_TEMPLATE';
export const CONTAINER_CHANGE_TEMPLATE_LINK = 'CONTAINER_CHANGE_TEMPLATE_LINK';
export const CONTAINER_EDIT_ELEMENT = 'CONTAINER_EDIT_ELEMENT';
export const CONTAINER_DELETE_ELEMENT = 'CONTAINER_DELETE_ELEMENT';


