export const PDF_SET_DATA = 'PDF_SET_DATA';
export const PDF_CLEAR_DATA = 'PDF_CLEAR_DATA';

export const PDF_SET_SETTINGS = 'PDF_SET_SETTINGS';

export const PDF_SET_SELECT = 'PDF_SET_SELECT';
export const PDF_SET_SELECT_SOME = 'PDF_SET_SELECT_SOME';
export const PDF_SET_SELECT_MOUSE_BOX = 'PDF_SET_SELECT_MOUSE_BOX';
export const PDF_CLEAR_SELECTS = 'PDF_CLEAR_SELECTS';

export const PDF_GROUP_ELEMENTS = 'PDF_GROUP_ELEMENTS';
export const PDF_UNGROUP_ELEMENTS = 'PDF_UNGROUP_ELEMENTS';

export const PDF_RESIZE_GROUP_ELEMENT = 'PDF_RESIZE_GROUP_ELEMENT';
export const PDF_MOVE_SELECT_CONTAINER = 'PDF_MOVE_SELECT_CONTAINER';
export const PDF_RESIZE_SELECT_CONTAINER = 'PDF_RESIZE_SELECT_CONTAINER';


export const PDF_ADD_ELEMENT = 'PDF_ADD_ELEMENT';
export const PDF_ADD_TEMPLATE = 'PDF_ADD_TEMPLATE';
export const PDF_CHANGE_TEMPLATE = 'PDF_CHANGE_TEMPLATE';
export const PDF_EDIT_ELEMENT = 'PDF_EDIT_ELEMENT';
export const PDF_DELETE_ELEMENT = 'PDF_DELETE_ELEMENT';

export const PDF_PASTE_STYLE_ELEMENT = 'PDF_PASTE_STYLE_ELEMENT';


