export const PDF_SET_DATA = 'CONTAINER_SET_DATA';
export const PDF_CLEAR_DATA = 'CONTAINER_CLEAR_DATA';

export const PDF_SET_SETTINGS = 'CONTAINER_SET_SETTINGS';

export const PDF_SET_SELECT = 'CONTAINER_SET_SELECT';
export const PDF_SET_SELECT_SOME = 'CONTAINER_SET_SELECT_SOME';
export const PDF_SET_SELECT_MOUSE_BOX = 'CONTAINER_SET_SELECT_MOUSE_BOX';
export const PDF_CLEAR_SELECTS = 'CONTAINER_CLEAR_SELECTS';

export const PDF_GROUP_ELEMENTS = 'CONTAINER_GROUP_ELEMENTS';
export const PDF_UNGROUP_ELEMENTS = 'CONTAINER_UNGROUP_ELEMENTS';

export const PDF_RESIZE_GROUP_ELEMENT = 'CONTAINER_RESIZE_GROUP_ELEMENT';
export const PDF_MOVE_SELECT_CONTAINER = 'CONTAINER_MOVE_SELECT_CONTAINER';
export const PDF_RESIZE_SELECT_CONTAINER = 'CONTAINER_RESIZE_SELECT_CONTAINER';


export const PDF_ADD_ELEMENT = 'CONTAINER_ADD_ELEMENT';
export const PDF_ADD_TEMPLATE = 'CONTAINER_ADD_TEMPLATE';
export const PDF_CHANGE_TEMPLATE = 'CONTAINER_CHANGE_TEMPLATE';
export const PDF_EDIT_ELEMENT = 'CONTAINER_EDIT_ELEMENT';
export const PDF_DELETE_ELEMENT = 'CONTAINER_DELETE_ELEMENT';

export const PDF_PASTE_STYLE_ELEMENT = 'CONTAINER_PASTE_STYLE_ELEMENT';


