export const TEMPLATE_SET_DATA = 'TEMPLATE_SET_DATA';
export const TEMPLATE_CLEAR_DATA = 'TEMPLATE_CLEAR_DATA';

export const TEMPLATE_SET_SETTINGS = 'TEMPLATE_SET_SETTINGS';

export const TEMPLATE_SET_SELECT = 'TEMPLATE_SET_SELECT';
export const TEMPLATE_SET_SELECT_SOME = 'TEMPLATE_SET_SELECT_SOME';
export const TEMPLATE_SET_SELECT_MOUSE_BOX = 'TEMPLATE_SET_SELECT_MOUSE_BOX';
export const TEMPLATE_CLEAR_SELECTS = 'TEMPLATE_CLEAR_SELECTS';

export const TEMPLATE_GROUP_ELEMENTS = 'TEMPLATE_GROUP_ELEMENTS';
export const TEMPLATE_UNGROUP_ELEMENTS = 'TEMPLATE_UNGROUP_ELEMENTS';

export const TEMPLATE_RESIZE_GROUP_ELEMENT = 'TEMPLATE_RESIZE_GROUP_ELEMENT';
export const TEMPLATE_MOVE_SELECT_CONTAINER = 'TEMPLATE_MOVE_SELECT_TEMPLATE';
export const TEMPLATE_RESIZE_SELECT_CONTAINER = 'TEMPLATE_RESIZE_SELECT_TEMPLATE';

export const TEMPLATE_ADD_ELEMENT = 'TEMPLATE_ADD_ELEMENT';
export const TEMPLATE_EDIT_ELEMENT = 'TEMPLATE_EDIT_ELEMENT';
export const TEMPLATE_DELETE_ELEMENT = 'TEMPLATE_DELETE_ELEMENT';
export const TEMPLATE_PASTE_ELEMENT = 'TEMPLATE_PASTE_ELEMENT';
export const TEMPLATE_MOVE_ELEMENT_MASTER = 'TEMPLATE_MOVE_ELEMENT_MASTER';
export const TEMPLATE_MOVE_ELEMENT_STATE = 'TEMPLATE_MOVE_ELEMENT_STATE';

export const TEMPLATE_SORT_LIST_STATE = 'TEMPLATE_SORT_STATE_LIST';
export const TEMPLATE_CHANGE_STATE = 'TEMPLATE_CHANGE_STATE';
export const TEMPLATE_CHANGE_VALUE_STATE = 'TEMPLATE_CHANGE_VALUE_STATE';
export const TEMPLATE_CHANGE_VISIBILITY_STATE = 'TEMPLATE_CHANGE_VISIBILITY_STATE';

export const TEMPLATE_ADD_STATE = 'TEMPLATE_ADD_STATE';
export const TEMPLATE_EDIT_STATE = 'TEMPLATE_EDIT_STATE';
export const TEMPLATE_EDIT_STATE_MASTER = 'TEMPLATE_EDIT_STATE_MASTER';
export const TEMPLATE_DELETE_STATE = 'TEMPLATE_DELETE_STATE';

export const TEMPLATE_DELETE_STATE_BY_VALUE = 'TEMPLATE_DELETE_STATE_BY_VALUE';
export const TEMPLATE_DELETE_STATE_BY_ELEMENT = 'TEMPLATE_DELETE_STATE_BY_ELEMENT';
export const TEMPLATE_DELETE_STATE_BY_PROPERTY = 'TEMPLATE_DELETE_STATE_BY_PROPERTY';

export const TEMPLATE_EDIT_ID_STATE = 'TEMPLATE_EDIT_ID_STATE';
export const TEMPLATE_CHANGE_TITLE_STATE = 'TEMPLATE_CHANGE_TITLE_STATE';

export const TEMPLATE_SET_MODE_MASTER = 'TEMPLATE_SET_MODE_MASTER';
export const TEMPLATE_SET_MODE_VARS = 'TEMPLATE_SET_MODE_VARS';
export const TEMPLATE_SET_MODE_EVENTS = 'TEMPLATE_SET_MODE_EVENTS';
