export const TEMPLATE_SET_DATA = 'TEMPLATE_SET_DATA';
export const TEMPLATE_CLEAR_DATA = 'TEMPLATE_CLEAR_DATA';

export const TEMPLATE_SET_SETTINGS = 'TEMPLATE_SET_SETTINGS';

export const TEMPLATE_SET_SELECT = 'TEMPLATE_SET_SELECT';
export const TEMPLATE_SET_SELECT_SOME = 'TEMPLATE_SET_SELECT_SOME';
export const TEMPLATE_CLEAR_SELECTS = 'TEMPLATE_CLEAR_SELECTS';

export const TEMPLATE_GROUP_ELEMENTS = 'TEMPLATE_GROUP_ELEMENTS';
export const TEMPLATE_UNGROUP_ELEMENTS = 'TEMPLATE_UNGROUP_ELEMENTS';

export const TEMPLATE_RESIZE_GROUP_ELEMENT = 'TEMPLATE_RESIZE_GROUP_ELEMENT';
export const TEMPLATE_MOVE_SELECT_CONTAINER = 'TEMPLATE_MOVE_SELECT_TEMPLATE';
export const TEMPLATE_RESIZE_SELECT_CONTAINER = 'TEMPLATE_RESIZE_SELECT_TEMPLATE';


export const TEMPLATE_ADD_ELEMENT = 'TEMPLATE_ADD_ELEMENT';
export const TEMPLATE_EDIT_ELEMENT = 'TEMPLATE_EDIT_ELEMENT';

export const TEMPLATE_CHANGE_VALUE_STATE = 'TEMPLATE_CHANGE_VALUE_STATE';
export const TEMPLATE_CHANGE_MASTER_STATE = 'TEMPLATE_CHANGE_MASTER_STATE';
export const TEMPLATE_CHANGE_OTHER_STATE = 'TEMPLATE_CHANGE_OTHER_STATE';

