import core from 'core';


function lang(item) {
  const id = item.lang || item.prop || item.id;
  if (langs[id] !== undefined) {
    return langs[id];
  }
  return ':' + id + ':';
}


export default lang;


const langs = {
  '1970': "-",
  '-': "-",
  Arial: "Arial",
  Monospace: "Monospace",
  'Sans-serif': "Sans-serif",
  Serif: "Serif",
  activeColor: "Активный цвет",
  alertjournals: "Выберите журнал тревог",
  alertjournalsAndAny: "Выберите журнал тревог",
  alignH: "Vertical",
  alignW: "Horizontal",
  animation: "Анимация",
  any: "Any",
  autoHideLabel: "Auto Hide Label",
  axisBottom: "Видимый",
  axisBottomDate: "Show Date",
  axisBottomTime: "Show Time",
  axisDynamic: "Dynamic",
  axisLabel: "Label",
  axisLeft: "Видимый",
  axisLeftLabel: "Label",
  axisLeftWidth: "Ширина",
  axisMax: "Max",
  axisMin: "Min",
  axisPosition: "Позиция",
  axisRight: "Видимый",
  axisRightLabel: "Label",
  axisRightWidth: "Ширина",
  axisWidth: "Ширина",
  backdropColor: "Backdrop Color",
  backgroundColor: "Цвет",
  backgroundImage: "Изображение",
  bar: "Bar",
  borderColor: "Цвет",
  borderRadius: "Радиус",
  borderSize: "Размер",
  borderStyle: "Стиль",
  bottom: "Снизу",
  bottom2: "Вниз",
  boxShadow: "Тень",
  button: "Button Confirm",
  buttonDate: "Date",
  buttonHome: "Home",
  buttonNavigate: "Navigate",
  buttonSize: "Size",
  buttonSync: "Sync",
  buttonsColor: "Color",
  center: "Центр",
  channelsx: "Выберите камеру",
  charts: "Выберите график",
  chartsAndAny: "Выберите график",
  code: "Код",
  color: "Color",
  colorHover: "Цвет наведении",
  colorRipple: "Цвет пульсации",
  dashed: "Dashed",
  day: "Day",
  devicesAndAny: "Выберите свойство",
  devicesx: "Выберите устройство",
  devprops: "Выберите свойство",
  devpropsAndAny: "Выберите свойство",
  dotted: "Dotted",
  end: "Справа",
  endAdornment: "End Adornment",
  fields: "Static Fields",
  fillGraph: "Fill Graph",
  fitH: "Высота",
  fitW: "Ширина",
  flipH: "Отразить по горизонтали",
  flipV: "Отразить по вертикали",
  fullHeight: "Full Height",
  fullWidth: "Full Width",
  function: "Function",
  gridColor: "Grid Color",
  groove: "Groove",
  h: "Высота",
  h2: "Высота снизу",
  hight: "Hight",
  hour: "Hour",
  hoverColor: "Hover Color",
  img: "Путь",
  imgColor: "Цвет",
  imgPosition: "Ориентация",
  imgRatio: "Соотношение",
  imgRotate: "Повернуть",
  imgSize: "Размер",
  inputMode: "Input Type",
  inset: "Inset",
  interval: "Interval",
  journals: "Выберите журнал",
  journalsAndAny: "Выберите журнал",
  label: "Label",
  labelColor: "Label Color",
  labelPlacement: "Label Placement",
  labelSize: "Label Seize",
  left: "Слева",
  legend: "Видимый",
  legendHeight: "Высота",
  legendLabel: "Label",
  legendWidth: "Ширина",
  line: "Line",
  lineColor: "Color",
  lineType: "Type",
  lines: "Static Lines",
  low: "Low",
  max: "Max",
  mean: "Mean",
  min: "Min",
  minute: "Minute",
  mount: "Month",
  moveable: "Moveable",
  none: "None",
  normalColor: "Base Color",
  number: "Number",
  opacity: "Непрозрачность",
  outfocus: "Out Focus",
  outset: "Outset",
  outsideClose: "Закрыть по клику",
  overflow: "Обрезать",
  overlayColor: "Цвет наложения",
  period: "Period",
  permanent: "Permanent",
  placeholder: "Placeholder",
  points: "Draw Points",
  positionCurentTime: "Position Curent Time",
  realtime: "Realtime",
  ridge: "Ridge",
  right: "Справа",
  rotate: "Повернуть",
  saveMode: "Save Mode",
  scrollX: "Horizontal",
  scrollY: "Vertical",
  smooth: "Smooth",
  solid: "Solid",
  start: "Слева",
  startAdornment: "Start Adornment",
  step: "Step",
  sum: "Sum",
  text: "Значение",
  textAlignH: "Горизонталь",
  textAlignV: "Вертикаль",
  textBold: "Насыщенность",
  textColor: "Цвет текста",
  textFontFamily: "Шрифт",
  textItalic: "Курсив",
  textRotate: "Повернуть",
  textSize: "Размер текста",
  thumbColor: "Thumb Color",
  timelinecharts: "Выберите график",
  timelinechartsAndAny: "Выберите график",
  top: "Сверху",
  trackColorLeft: "Track Color Left",
  trackColorRight: "Track Color Right",
  up: "Вверх",
  url: "Url",
  value: "Value",
  viscontx: "Выберите контейнер",
  visible: "Видимый",
  w: "Ширина",
  w2: "Ширина справа",
  week: "Week",
  x: "X",
  y: "Y",
  zIndex: "Положение элемента",
  Позиция: "Позиция",
  _settings_dev: 'Настройки разработки',
  grid: 'Сетка',
  scale: 'Масштаб',
  devBackgroundColor: 'Фон',
  bind: 'Привязка',
  link: 'Ссылка',
  prop_link: 'Привязать',
  prop_unlink: 'Отвязать',
  prop_up: 'Вверх',
  prop_down: 'Вниз',
  prop_del: 'Удалить',
  cmd_dev: 'Команда устройства',
  run_script: 'Запуск сценария',
  set_val: 'Установить значение',
  show_dialog: 'Показать диалог',
  init_dialog: 'Начальный диалог',
  close_dialog: 'Закрыть диалог',
  сmd_plugin: 'Команда плагина',
  go_layout: 'Переход на экран',
  run_vscript: 'Скрипт визуализации',
  full_screen: 'Полный экран',
  refresh_layout: 'Обновить экран',
  exit: 'Выход',
  add_elem: 'Добавить элемент',
  add_container: 'Добавить контейнер',
  add_template: 'Добавить шаблон',
  group: 'Сгруппировать',
  ungroup: 'Разгруппировать',
  copy: 'Копировать',
  paste: 'Вставить',
  copy_style: 'Копировать стиль',
  paste_style: 'Вставить стиль',
  del: 'Удалить',
  relink: 'Перепривязать',
  edit_template: 'Редактировать шаблон',
  edit_container: 'Редактировать контейнер',
  appbar_ui: 'user interface',
  appbar_settings: 'server settings',
  appbar_import: 'import',
  appbar_bug: 'Сообщить о проблеме',
  appbar_help: 'help',
  appbar_network_ok: 'connection established',
  appbar_network_err: 'connection disconnected',
  appbar_exit: 'exit',
  layout: 'Экран',
  container: 'Контейнер',
  template: 'Шаблон',
  dialog: 'Диалог',
  vars: 'Переменные',
  var: 'Переменная',
  actions: 'Действия',
  no_props: 'No properties',
  no_data: "It's empty is here",
  _aggregate: "Aggregate",
  _axis: "Axis Left / Right",
  _axis_bottom: "Axis Bottom",
  _axis_left: "Axis Left",
  _axis_right: "Axis Right",
  _background: "Фон",
  _border: "Рамка",
  _button: "Кнопка",
  _buttons: "Buttons",
  _chart: "Chart",
  _chart_multi: "Chart",
  _chart_timeline: "Chart Timeline",
  _checkbox: "Checkbox",
  _content_align: "Content Align",
  _content_fit: "Content Fit",
  _content_scroll: "Content Scroll",
  _decoration: "Украшение",
  _dialog: "Диалог",
  _effects: "Эффекты",
  _html: "Html",
  _iframe: "Iframe",
  _image: "Изображение",
  _input: "Input",
  _legend: "Legend",
  _line: "Line",
  _position: "Позиция",
  _slider: "Slider",
  _text: "Текст",
  _transform: "Преобразовать",
}