export const TEMPLATE_SET_DATA = 'TEMPLATE_SET_DATA';
export const TEMPLATE_FORCE_DATA = 'TEMPLATE_FORCE_DATA';

export const TEMPLATE_SET_POSITION_LAYOUT = 'TEMPLATE_SET_POSITION_LAYOUT';
export const TEMPLATE_SET_POSITION_CONTAINER = 'TEMPLATE_SET_POSITION_CONTAINER';
export const TEMPLATE_SET_PROPERTIES_CONTAINER = 'TEMPLATE_SET_PROPERTIES_CONTAINER';


export const TEMPLATE_SET_POSITION_GROUP_CONTAINER = 'TEMPLATE_SET_POSITION_GROUP_CONTAINER';
export const TEMPLATE_SET_RESIZE_GROUP_CONTAINER = 'TEMPLATE_SET_RESIZE_GROUP_CONTAINER';
export const TEMPLATE_SET_SETTINGS_CONTAINER = 'TEMPLATE_SET_SETTINGS_CONTAINER';

export const TEMPLATE_ADD_CONTAINER = 'TEMPLATE_ADD_CONTAINER';
export const TEMPLATE_SELECT_BLOCK = 'TEMPLATE_SELECT_BLOCK';
export const TEMPLATE_SELECT_ONE_CONTAINER = 'TEMPLATE_SELECT_ONE_CONTAINER';
export const TEMPLATE_SELECT_MULTI_CONTAINERS = 'TEMPLATE_SELECT_MULTI_CONTAINERS';
export const TEMPLATE_CLEAR_ALL_SELECTS = 'TEMPLATE_CLEAR_ALL_SELECTS';

export const TEMPLATE_SET_GROUP = 'TEMPLATE_SET_GROUP';
export const TEMPLATE_UNSET_GROUP = 'TEMPLATE_UNSET_GROUP';


