export const APP_LAYOUT_DIALOG_SET_DATA = 'APP_LAYOUT_DIALOG_SET_DATA';

export const APP_LAYOUT_DIALOG_UPDATE_ELEMENTS = 'APP_LAYOUT_DIALOG_UPDATE_ELEMENTS';
export const APP_LAYOUT_DIALOG_SYNC_CHARTS_LAYOUT = 'APP_LAYOUT_DIALOG_SYNC_CHARTS_LAYOUT';